---

# Navigation links
nav:
  # - name: "5pani2pesci"
  #   url: "/"

  # - name: "Gallerie"
  #   url: "/gallerie"

  # - name: "Chi siamo"
  #   url: "/chi-siamo"


# Site settings
title: 5p2p | weddings
email: weddings@5p2p.it
description: "Fotografia e Video per Matrimoni da Dio"

footer: >
  Al centro c'è il vostro sacramento, noi vi facciamo solo le foto. 
  <b>5pani2pesci</b> è un <a href="http://5p2p.it">progetto di evangelizzazione</a> 
  per scoprire <b>l'amore vero,</b> quello che ti cambia la vita. 
  Tutto il ricavato ottenuto dai servizi fotografici è finalizzato 
  per questa attività. <a href="/">Per maggiori informazioni.</a> 

url: "http://weddings.5p2p.it"
favicon: /assets/images/logo/5p2p-logo.png
logo: /assets/images/logo/5p2p-logo.png

# Build settings
basename: "/"
assets: "/assets"
markdown: kramdown
permalink: /:year/:title

# Collections
collections:
  pages:
    output: true
    permalink: /:title

# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "gallery"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "page"
